version: '3.4'

services:
  app:
    container_name: culqipay-backend
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - JWT_SECRET=culqiTechTest
      - JWT_EXPIRATION_TIME=1m
      - REDIS_HOST=redis-14581.c309.us-east-2-1.ec2.cloud.redislabs.com
      - REDIS_PASSWORD=a04Kw6lEciUaKm5xjMDP5NL9ggxx0qKI
      - REDIS_PORT=14581
      - REDIS_DEFAULT_TTL=60
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start